
//Prerequisite: Curl is installed

//Part 1: The first part is a command which accesses the github repositories from paul-ocalla.
//        The result is returned in the form of json. 

//part 2: In part 2, I used curl commands to create a repository for the data visualization project.


 //Access all repositories from username paul-ocalla
 curl -X GET -u paul-ocalla:0b160d18fbe380db77b957d5a60ac1c0f4803365 https://api.github.com/users/paul-ocalla/repos 


 //Create new repository for GitHub API visualization project
 curl -u paul-ocalla:0b160d18fbe380db77b957d5a60ac1c0f4803365 https://api.github.com/user/repos -d '{"name":"Data_Visualization"}'
